name: Moonfin
options:
  bundleIdPrefix: com.moonfin
  deploymentTarget:
    tvOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.1.1"
    CURRENT_PROJECT_VERSION: "20"
    DEVELOPMENT_TEAM: ""

packages:
  Nuke:
    url: https://github.com/kean/Nuke
    from: "12.7.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"
  MPVKit:
    url: https://github.com/mpvkit/MPVKit
    from: "0.41.0"

targets:
  Moonfin:
    type: application
    platform: tvOS
    deploymentTarget: "16.0"
    preBuildScripts:
      - name: Patch MPVKit Module Maps
        script: |
          "${PROJECT_DIR}/scripts/patch-modulemaps.sh"
        basedOnDependencyAnalysis: false
    sources:
      - path: Moonfin
        excludes:
          - "**/Tests/**"
    resources:
      - path: Moonfin/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.moonfin.app
        INFOPLIST_FILE: Moonfin/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: Moonfin/Resources/Moonfin.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: Moonfin/Moonfin-Bridging-Header.h
    dependencies:
      - package: Nuke
        product: NukeUI
      - package: Nuke
      - package: KeychainAccess
      - package: MPVKit
        product: MPVKit
      - target: MoonfinTopShelf
        embed: true

  MoonfinTopShelf:
    type: app-extension
    platform: tvOS
    deploymentTarget: "16.0"
    sources:
      - path: MoonfinTopShelf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.moonfin.app.topshelf
        INFOPLIST_FILE: MoonfinTopShelf/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: MoonfinTopShelf/MoonfinTopShelf.entitlements

schemes:
  Moonfin:
    build:
      targets:
        Moonfin: all
    run:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release
    profile:
      config: Release
